"""Organisation-Wide Change Intelligence API router (Stage 17).

Handles HTTP concerns only: routing, request parsing, response serialisation,
and HTTP error translation. All business logic lives in
OrganisationChangeIntelligenceService.

Route table
-----------
GET /api/v1/changes         Return all detected organisation-wide changes (read-only)
GET /api/v1/changes/summary Return structured aggregate summary of changes (read-only)

Both endpoints are strictly read-only. No POST/PUT/PATCH/DELETE endpoints exist
because changes are computed on demand and never persisted.

Changes are deterministic: the same repository state and the same evaluation time
always produce the same response.

Dependency wiring
-----------------
We use the same shared in-memory repository singletons as all other API endpoints,
imported from app.api.entities. This ensures the change intelligence service
sees data created via POST /meetings and POST /entities/mentions.

Filtering
---------
GET /api/v1/changes supports optional query parameters for filtering:
  - change_type: Only return changes of this type.
  - severity:    Only return changes at this severity level.
  - entity_id:   Only return changes for this specific entity.
  - meeting_id:  Only return changes attributed to this specific meeting.
  - start_date:  Only return changes with detected_at >= start_date (ISO 8601).
  - end_date:    Only return changes with detected_at <= end_date (ISO 8601).
  - limit:       Maximum number of changes to return (1-1000).
"""

from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, Depends, Query

from app.api.auth import Authorisation, get_request_context, require_permission
from app.auth.models import Permission
from app.models.organisation_change import (
    OrganisationChangeSeverity,
    OrganisationChangeType,
)
from app.schemas.changes import (
    OrganisationChangeSchema,
    OrganisationChangeSeveritySchema,
    OrganisationChangeSummaryResponse,
    OrganisationChangeSummarySchema,
    OrganisationChangesResponse,
    OrganisationChangeTypeSchema,
)
from app.services.organisation_change_intelligence_service import (
    OrganisationChangeIntelligenceService,
)
from app.temporal.state_interpreter import KeywordStateInterpreter
from app.temporal.transition_policy import DefaultTransitionPolicy

router = APIRouter(prefix="/changes", tags=["Changes"])


def get_organisation_change_intelligence_service(
    ctx: Authorisation = Depends(get_request_context),
) -> OrganisationChangeIntelligenceService:
    """FastAPI dependency that provides a tenant-scoped OrganisationChangeIntelligenceService.

    All composed intelligence (insights, attention, graphs, impacts) operates
    on the request's tenant-scoped repositories, so organisation-wide
    calculations never cross tenant boundaries.
    """
    from app.api.entities import _build_current_revision_lookup

    return OrganisationChangeIntelligenceService(
        entity_repo=ctx.repos.entities,
        mention_repo=ctx.repos.mentions,
        meeting_repo=ctx.repos.meetings,
        interpreter=KeywordStateInterpreter(),
        policy=DefaultTransitionPolicy(),
        dependency_repo=ctx.repos.dependencies,
        current_revision_lookup=_build_current_revision_lookup(ctx),
    )


@router.get(
    "/summary",
    response_model=OrganisationChangeSummaryResponse,
    summary="Get structured aggregate summary of organisation-wide changes",
    description=(
        "Return a deterministic, structured aggregate summary of all detected "
        "organisation-wide changes.\\n\\n"
        "**This is never generated by an LLM.** All fields are deterministic counts "
        "derived from the same intelligence signals as GET /changes.\\n\\n"
        "Includes counts by severity, entity groupings, and categorised entity lists "
        "(blocked, resolved, regressed, reopened, stale).\\n\\n"
        "This endpoint evaluates current state dynamically on read and never modifies data."
    ),
)
def get_changes_summary(
    start_date: Optional[datetime] = Query(
        default=None,
        description="Only include changes with detected_at >= start_date (ISO 8601, UTC).",
    ),
    end_date: Optional[datetime] = Query(
        default=None,
        description="Only include changes with detected_at <= end_date (ISO 8601, UTC).",
    ),
    service: OrganisationChangeIntelligenceService = Depends(
        get_organisation_change_intelligence_service
    ),
    _ctx: Authorisation = Depends(require_permission(Permission.INTELLIGENCE_READ)),
) -> OrganisationChangeSummaryResponse:
    """Return a structured aggregate summary of organisation-wide changes."""
    ref_time = datetime.now(timezone.utc)
    summary = service.get_summary(
        current_time=ref_time,
        start_date=start_date,
        end_date=end_date,
    )
    return OrganisationChangeSummaryResponse(
        summary=OrganisationChangeSummarySchema(
            total_changes=summary.total_changes,
            critical_changes=summary.critical_changes,
            high_changes=summary.high_changes,
            medium_changes=summary.medium_changes,
            info_changes=summary.info_changes,
            newly_blocked_entities=summary.newly_blocked_entities,
            newly_resolved_entities=summary.newly_resolved_entities,
            regressed_entities=summary.regressed_entities,
            reopened_entities=summary.reopened_entities,
            new_dependency_count=summary.new_dependency_count,
            expanded_impact_count=summary.expanded_impact_count,
            stale_entities=summary.stale_entities,
            changes_by_entity=summary.changes_by_entity,
        ),
        evaluated_at=ref_time,
    )


@router.get(
    "",
    response_model=OrganisationChangesResponse,
    summary="Get all detected organisation-wide changes",
    description=(
        "Return a deterministic, read-only list of all detected organisation-wide "
        "changes aggregated from all existing ThreadLine intelligence "
        "(insights, attention, dependency graph, impact analysis).\\n\\n"
        "**Change types** (13 deterministic types):\\n"
        "- **STATE_OPENED** (INFO): Entity first observed in OPEN state.\\n"
        "- **STATE_STARTED** (INFO): Entity transitioned to IN_PROGRESS.\\n"
        "- **STATE_BLOCKED** (HIGH): Entity transitioned to BLOCKED.\\n"
        "- **STATE_RESOLVED** (INFO): Entity transitioned to RESOLVED.\\n"
        "- **STATE_REGRESSED** (HIGH): Entity moved from IN_PROGRESS/OPEN to BLOCKED.\\n"
        "- **STATE_REOPENED** (HIGH): Reopen attempt on a RESOLVED entity.\\n"
        "- **REPEATED_UNRESOLVED** (MEDIUM): Entity observed multiple times without progress.\\n"
        "- **RISK_ESCALATED** (CRITICAL): Entity has CRITICAL attention due to BLOCKED state.\\n"
        "- **RISK_DEESCALATED** (INFO): Entity resolved, risk removed.\\n"
        "- **NEW_DEPENDENCY** (MEDIUM): Explicit DEPENDS_ON or BLOCKS relationship found.\\n"
        "- **DEPENDENCY_EXPANDED** (MEDIUM): Transitive dependency chain (depth >= 2) found.\\n"
        "- **IMPACT_EXPANDED** (MEDIUM): Entity has inbound risk impact associations.\\n"
        "- **ENTITY_BECAME_STALE** (HIGH): Entity crossed staleness threshold.\\n\\n"
        "**Important constraints**:\\n"
        "- CO_OCCURS_WITH relationships are NEVER promoted to dependency changes.\\n"
        "- All changes are grounded in traceable evidence from existing intelligence signals.\\n"
        "- No LLM, RAG, or probabilistic inference is used.\\n\\n"
        "**Ordering**: severity DESC, change_type priority ASC, "
        "detected_at DESC, entity_id ASC, change_id ASC.\\n\\n"
        "This endpoint evaluates current state dynamically on read and never modifies data."
    ),
)
def get_changes(
    change_type: Optional[OrganisationChangeTypeSchema] = Query(
        default=None,
        description="Filter to only return changes of this type.",
    ),
    severity: Optional[OrganisationChangeSeveritySchema] = Query(
        default=None,
        description="Filter to only return changes at this severity level.",
    ),
    entity_id: Optional[str] = Query(
        default=None,
        description="Filter to only return changes for this specific entity.",
    ),
    meeting_id: Optional[str] = Query(
        default=None,
        description="Filter to only return changes attributed to this meeting.",
    ),
    start_date: Optional[datetime] = Query(
        default=None,
        description="Only return changes with detected_at >= start_date (ISO 8601, UTC).",
    ),
    end_date: Optional[datetime] = Query(
        default=None,
        description="Only return changes with detected_at <= end_date (ISO 8601, UTC).",
    ),
    limit: Optional[int] = Query(
        default=None,
        ge=1,
        le=1000,
        description="Maximum number of changes to return (1-1000).",
    ),
    service: OrganisationChangeIntelligenceService = Depends(
        get_organisation_change_intelligence_service
    ),
    _ctx: Authorisation = Depends(require_permission(Permission.INTELLIGENCE_READ)),
) -> OrganisationChangesResponse:
    """Return all detected organisation-wide changes."""
    ref_time = datetime.now(timezone.utc)

    # Map schema enums to domain model enums for the service.
    domain_change_type: Optional[OrganisationChangeType] = None
    if change_type is not None:
        domain_change_type = OrganisationChangeType(change_type.value)

    domain_severity: Optional[OrganisationChangeSeverity] = None
    if severity is not None:
        domain_severity = OrganisationChangeSeverity(severity.value)

    changes = service.get_changes(
        current_time=ref_time,
        change_type=domain_change_type,
        severity=domain_severity,
        entity_id=entity_id,
        meeting_id=meeting_id,
        start_date=start_date,
        end_date=end_date,
        limit=limit,
    )

    change_schemas = [
        OrganisationChangeSchema(
            change_id=c.change_id,
            entity_id=c.entity_id,
            change_type=OrganisationChangeTypeSchema(c.change_type.value),
            severity=OrganisationChangeSeveritySchema(c.severity.value),
            detected_at=c.detected_at,
            meeting_id=c.meeting_id,
            mention_id=c.mention_id,
            source_text=c.source_text,
            previous_state=c.previous_state,
            current_state=c.current_state,
            insight_id=c.insight_id,
            dependency_path=c.dependency_path,
            impact_count=c.impact_count,
            related_entity_ids=c.related_entity_ids,
            evidence=c.evidence,
        )
        for c in changes
    ]

    # Compute aggregate counts from the returned changes.
    critical_count = sum(
        1 for c in change_schemas if c.severity == OrganisationChangeSeveritySchema.CRITICAL
    )
    high_count = sum(
        1 for c in change_schemas if c.severity == OrganisationChangeSeveritySchema.HIGH
    )
    medium_count = sum(
        1 for c in change_schemas if c.severity == OrganisationChangeSeveritySchema.MEDIUM
    )
    info_count = sum(
        1 for c in change_schemas if c.severity == OrganisationChangeSeveritySchema.INFO
    )

    return OrganisationChangesResponse(
        total_changes=len(change_schemas),
        critical_changes=critical_count,
        high_changes=high_count,
        medium_changes=medium_count,
        info_changes=info_count,
        changes=change_schemas,
        evaluated_at=ref_time,
    )
